baseURL = "angry-cray-9570ec.netlify.app"
languageCode = "en-us"
title = "PS-blog"
theme = "m10c"
[params]
	avatar = "avatar.png"
	author = "PS"
	description = "A random way of sharing my thoughts"
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
